In [1]:
import numpy as np

In [2]:
array1=np.array([1,2,3,4,5,6])
array1

array([1, 2, 3, 4, 5, 6])

In [3]:
type(array1)

numpy.ndarray

In [4]:
array1.shape

(6,)

In [5]:
array2=array1.reshape(1,6)

In [7]:
array2

array([[1, 2, 3, 4, 5, 6]])

In [9]:
arr3=np.arange(0,51,2)
arr3

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50])

In [13]:
len(arr3)

26

In [14]:
arr4=arr3.reshape(2,13)
arr4

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24],
       [26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50]])

In [15]:
arr5=arr3.reshape(13,2)

In [16]:
arr5

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [20, 22],
       [24, 26],
       [28, 30],
       [32, 34],
       [36, 38],
       [40, 42],
       [44, 46],
       [48, 50]])

In [18]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
arr3.dtype  # gives data type

dtype('int64')

In [ ]:
arr3.ndim # gives number of dimensions

1

In [26]:
array2.ndim

2

In [ ]:
arr3.size  # tells no of elemnts in the array

26

In [29]:
arr3.itemsize    # gives size in bytes

8

Numpy Vectorized Opearations


In [30]:
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([1,2,3,4,5,6])

# Element wise operation

print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[ 2  4  6  8 10 12]
[0 0 0 0 0 0]
[ 1  4  9 16 25 36]
[1. 1. 1. 1. 1. 1.]


In [33]:
# Universal Functions
array=np.array([10,23,22,21,77])

print(np.sqrt(array))
print(np.sin(array))
print(np.cos(array))
print(np.log(array))
print(np.exp(array))

[3.16227766 4.79583152 4.69041576 4.58257569 8.77496439]
[-0.54402111 -0.8462204  -0.00885131  0.83665564  0.99952016]
[-0.83907153 -0.53283302 -0.99996083 -0.54772926 -0.03097503]
[2.30258509 3.13549422 3.09104245 3.04452244 4.34380542]
[2.20264658e+04 9.74480345e+09 3.58491285e+09 1.31881573e+09
 2.75851345e+33]


In [43]:
# Slicing and Indexing Operations

arr=np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])

In [44]:
arr[0]

array([1, 2, 3, 4])

In [45]:
print(arr[0][0])

1


In [47]:
print(arr[1:,2:,])

[[ 7  8]
 [11 12]]


In [48]:
print(arr[0:2,2:])

[[3 4]
 [7 8]]


In [49]:
# Modifying array elements

arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [50]:
arr[1:,2:,]=100
print(arr)

[[100   2   3   4]
 [  5   6 100 100]
 [  9  10 100 100]]


In [51]:
# Logical Opeartions
listee=np.array([1,2,3,4,5,7,9])
print(listee>3)

[False False False  True  True  True  True]


In [53]:
listee[listee>3]

array([4, 5, 7, 9])

In [60]:
listee[(listee>=5) & (listee<9)]

array([5, 7])