In [1]:
import numpy as np

In [2]:
array1=np.array([1,2,3,4,5,6])
array1

array([1, 2, 3, 4, 5, 6])

In [3]:
type(array1)

numpy.ndarray

In [4]:
array1.shape

(6,)

In [5]:
array2=array1.reshape(1,6)

In [7]:
array2

array([[1, 2, 3, 4, 5, 6]])

In [9]:
arr3=np.arange(0,51,2)
arr3

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50])

In [13]:
len(arr3)

26

In [14]:
arr4=arr3.reshape(2,13)
arr4

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24],
       [26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50]])

In [15]:
arr5=arr3.reshape(13,2)

In [16]:
arr5

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [20, 22],
       [24, 26],
       [28, 30],
       [32, 34],
       [36, 38],
       [40, 42],
       [44, 46],
       [48, 50]])

In [18]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
arr3.dtype  # gives data type

dtype('int64')

In [ ]:
arr3.ndim # gives number of dimensions

1

In [26]:
array2.ndim

2

In [ ]:
arr3.size  # tells no of elemnts in the array

26

In [29]:
arr3.itemsize    # gives size in bytes

8

Numpy Vectorized Opearations


In [30]:
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([1,2,3,4,5,6])

# Element wise operation

print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[ 2  4  6  8 10 12]
[0 0 0 0 0 0]
[ 1  4  9 16 25 36]
[1. 1. 1. 1. 1. 1.]
